/* eslint-disable no-sync */

import fs from 'fs'

import {
  expect,
  fakeCodexCapturePath,
  fakeCodexControlPath,
  test,
} from './e2e-fixtures'
import {
  getSmokeRepoHeadMessage,
  getSmokeRepoStatus,
  smokeRepoFileContents,
  smokeRepoFileName,
  smokeRepoPath,
} from './test-helpers'

test.describe.configure({ mode: 'serial' })

async function finishWelcome(page: import('@playwright/test').Page) {
  await page.waitForFunction(
    () =>
      (document.getElementById('desktop-app-container')?.innerHTML.length ??
        0) > 100,
    null,
    { timeout: 30_000 }
  )
  const skip = page.locator('a.skip-button')
  if (await skip.isVisible().catch(() => false)) {
    await skip.click()
    await page.locator('input[placeholder="Your Name"]').fill('Test User')
    await page
      .locator('input[placeholder="your-email@example.com"]')
      .fill('test.user@example.invalid')
    await page.getByRole('button', { name: 'Finish' }).click()
    await page.locator('#welcome').waitFor({ state: 'hidden' })
  }
}

async function openSmokeRepository(page: import('@playwright/test').Page) {
  const repoFile = page
    .locator(`//*[contains(normalize-space(), "${smokeRepoFileName}")]`)
    .first()
  if (!(await repoFile.isVisible().catch(() => false))) {
    const existingDialog = page.locator('dialog#add-existing-repository')
    if (!(await existingDialog.isVisible().catch(() => false))) {
      await page
        .getByRole('button', {
          name: /Add an Existing Repository from your Local Drive/i,
        })
        .click()
    }
    await existingDialog.waitFor({ state: 'visible', timeout: 15_000 })
    const pathInput = existingDialog.locator(
      'input[placeholder="repository path"]'
    )
    await pathInput.fill(smokeRepoPath)
    await existingDialog
      .getByRole('button', { name: /Add repository/i })
      .click()
  }
  await repoFile.waitFor({ state: 'visible', timeout: 15_000 })
  await repoFile.click()
  await page.locator('.diff-container').waitFor({ state: 'visible' })
}

function capturedMessages() {
  if (!fs.existsSync(fakeCodexCapturePath)) {
    return []
  }
  return fs
    .readFileSync(fakeCodexCapturePath, 'utf8')
    .trim()
    .split(/\r?\n/)
    .filter(Boolean)
    .map(line => JSON.parse(line) as Record<string, unknown>)
}

test('drives selected changes through the real UI and isolated App Server IPC', async ({
  mainWindow: page,
}) => {
  test.skip(
    process.env.DESKTOP_E2E_FAKE_CODEX !== '1',
    'Run with DESKTOP_E2E_FAKE_CODEX=1.'
  )
  await finishWelcome(page)
  await openSmokeRepository(page)

  const unselectedFile = page
    .locator('.file')
    .filter({ hasText: 'unselected-secret.txt' })
  await unselectedFile.waitFor({ state: 'visible', timeout: 15_000 })
  await unselectedFile
    .locator('input[type="checkbox"]')
    .uncheck({ force: true })

  const summary = page.getByLabel('Commit summary')
  await summary.fill('')
  const initialHead = getSmokeRepoHeadMessage()
  const generate = page.getByRole('button', {
    name: 'Generate commit message with Codex',
  })
  await expect(generate).toBeEnabled()
  await generate.click()

  const consent = page.getByRole('alertdialog', {
    name: 'Share selected changes with OpenAI?',
  })
  await expect(consent).toBeVisible()
  await consent.getByRole('button', { name: 'Share selected changes' }).click()

  await expect(summary).toHaveValue('Describe selected change', {
    timeout: 15_000,
  })
  await expect(page.getByLabel('Commit description')).toHaveValue(
    'Generated by the deterministic Codex fixture.'
  )

  await expect
    .poll(() => capturedMessages().length, { timeout: 10_000 })
    .toBeGreaterThanOrEqual(2)
  const turnStart = capturedMessages().find(
    message => message.method === 'turn/start'
  ) as { params?: { input?: Array<{ text?: string }> } } | undefined
  const prompt = turnStart?.params?.input?.[0]?.text ?? ''
  expect(prompt).toContain(smokeRepoFileContents)
  expect(prompt).not.toContain('UNSELECTED_PRIVATE_CONTENT')
  expect(getSmokeRepoHeadMessage()).toBe(initialHead)
  expect(getSmokeRepoStatus()).not.toBe('')
  await expect(generate).toBeVisible()
})

test('cancels a slow turn without an error dialog', async ({
  mainWindow: page,
}) => {
  test.skip(process.env.DESKTOP_E2E_FAKE_CODEX !== '1')
  fs.writeFileSync(fakeCodexControlPath, 'slow')
  const generationsBefore = capturedMessages().filter(
    message => message.method === 'turn/start'
  ).length
  const summary = page.getByLabel('Commit summary')
  await summary.fill('')
  await page.getByLabel('Commit description').fill('')
  await page
    .getByRole('button', { name: 'Generate commit message with Codex' })
    .click()

  const cancel = page.getByRole('button', {
    name: 'Cancel generating commit details',
  })
  await expect(cancel).toBeVisible()
  await expect
    .poll(
      () =>
        capturedMessages().filter(message => message.method === 'turn/start')
          .length,
      { timeout: 10_000 }
    )
    .toBe(generationsBefore + 1)
  await cancel.click()

  await expect(
    page.getByRole('button', { name: 'Generate commit message with Codex' })
  ).toBeVisible()
  await expect(page.locator('dialog#app-error')).not.toBeVisible()
  await expect
    .poll(
      () =>
        capturedMessages().some(message => message.method === 'turn/interrupt'),
      { timeout: 10_000 }
    )
    .toBe(true)
})

test('preserves existing text after invalid output and starts a fresh turn', async ({
  mainWindow: page,
}) => {
  test.skip(process.env.DESKTOP_E2E_FAKE_CODEX !== '1')
  fs.writeFileSync(fakeCodexControlPath, 'invalid')
  const summary = page.getByLabel('Commit summary')
  await summary.fill('Keep my existing summary')
  const generationsBefore = capturedMessages().filter(
    message => message.method === 'turn/start'
  ).length

  await page
    .getByRole('button', { name: 'Generate commit message with Codex' })
    .click()
  const override = page.locator(
    'dialog#generate-commit-message-override-warning'
  )
  await override.waitFor({ state: 'visible' })
  await override.getByRole('button', { name: 'Override' }).click()

  const error = page.locator('dialog#app-error')
  await error.waitFor({ state: 'visible', timeout: 15_000 })
  await expect(summary).toHaveValue('Keep my existing summary')
  await expect
    .poll(
      () =>
        capturedMessages().filter(message => message.method === 'turn/start')
          .length
    )
    .toBe(generationsBefore + 1)
})
